import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/app/components/theme-provider";
import Navbar from "./components/Navbar";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import prisma from "@/lib/db";

const poppins = Poppins<any>({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Notedly - The ultimate note taking app",
  description: "Generated by create next app",
};

async function getUserData(id: string) {
  if (id) {
    const user = await prisma.user.findUnique({
      where: {
        id: id,
      },
      select: {
        colorTheme: true,
      },
    });

    return user;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = await getKindeServerSession();
  const user = await getUser();

  const user_data = await getUserData(user?.id as string);
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${
          user_data?.colorTheme ?? "theme-violet"
        }`}
      >
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
